---
- name: Deploy Application
  hosts: your_production_servers
  become: yes
  vars:
    app_name: "springbootapp"
    image: "mayma/springbootapp:latest"
    container_name: "{{ app_name }}_container"

  tasks:
    - name: Pull latest Docker image
      docker_image:
        name: "{{ image }}"
        source: pull

    - name: Remove existing container
      docker_container:
        name: "{{ container_name }}"
        state: absent

    - name: Create and start container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image }}"
        state: started
        restart_policy: always
        ports:
          - "80:8080"  # Adjust port mappings as needed

    - name: Clean up old Docker images
      docker_image:
        name: "{{ image }}"
        state: absent
        force_absent: yes
